In [14]:
import numpy as np
import math

In [15]:
class Dense:
    input_size = -1
    number_of_neurons = 0
    def __init__(self, units: int, input_size=-1):
        """
        input_size for the first Dense layer should not be -1, it should be > 0
        """
        if units<=0:
            raise Exception(f"number of neurons for a layer should be > 0")
        self.number_of_neurons = units
        self.input_size = input_size

In [59]:
class sequencial:
    model = []
    input_size = 0
    def __init__(self, layers: list[Dense]):
        if len(layers)==0:
            raise Exception(f"model should have atleast 1 layer")
        if layers[0].input_size<=0:
            raise Exception(f"first layer of the model should have the input size > 0")

        first_layer = layers[0]
        number_of_w = first_layer.input_size
        self.input_size = first_layer.input_size

        # we have to make a numpy matrix of size: number_of_w x first_layer.number_of_neurons
        w = np.random.randint(0, 3, size=(number_of_w, first_layer.number_of_neurons))
        b = np.random.randint(0, 3, size=(1, first_layer.number_of_neurons))
        current_layer = []
        current_layer.append(w)
        current_layer.append(b)
        self.model.append(current_layer)

        # now handle the other layers as the general rule
        for i in range(1, len(layers)):
            curr_layer = layers[i]
            number_of_w = self.model[-1][0].shape[1]
            w = np.random.randint(0, 3, size=(number_of_w, curr_layer.number_of_neurons))
            b = np.random.randint(0, 3, size=(1, curr_layer.number_of_neurons))
            current_layer = []
            current_layer.append(w)
            current_layer.append(b)
            self.model.append(current_layer)

        print(f"model created!")

    def summary(self):
        return self.model

    def predict(self, X: np.ndarray) -> np.ndarray:
        if X.shape[1] != self.input_size:
            raise Exception(f"input size mismatch!")
        for i in range(len(self.model)):
            print(X)
            current_w = self.model[i][0]
            current_b = self.model[i][1]
            X = np.matmul(X, current_w) + current_b
        return X

In [60]:
model = sequencial([
    Dense(units=5, input_size=4),
    Dense(units=3),
    Dense(units=1)])

model created!


In [61]:
model.summary()

[[array([[0, 1, 1, 0, 0],
         [0, 2, 1, 1, 0],
         [2, 2, 2, 2, 0],
         [1, 1, 1, 1, 1]]),
  array([[1, 0, 0, 2, 0]])],
 [array([[0, 0, 1],
         [0, 1, 1],
         [0, 0, 2],
         [0, 1, 0],
         [1, 2, 1]]),
  array([[0, 1, 1]])],
 [array([[2],
         [2],
         [0]]),
  array([[0]])]]

In [62]:
X = np.random.randint(0, 3, size=(1, 4))

In [63]:
X

array([[2, 2, 0, 2]])

In [64]:
model.predict(X)

[[2 2 0 2]]
[[3 8 6 6 2]]
[[ 2 19 26]]


array([[42]])